### ISSUE TITLE
Input identifier in update event

### ISSUE THREAD

**Issue by razzeee** [abadi199/elm-input-extra#10]
I'm having a problem, as I have a List of Items and try to draw an input for each of those items.

Now I need to figure out which input was updated and match that back to my datastructure in my update function. But I only have the new value available and no reference to which item in my list it belongs.

**Comment by abadi199** [comment]
Hi @Razzeee , if you can provide a code sample, I can probably help you better. If you have a unique `Id` for those items, you can include that `Id` in your `Msg`, so your message type will look like this:
```elm
type Msg = InputUpdated String String

...
Input.Text.input
    { maxLength = Nothing
    , onInput = InputUpdated "Input1" -- partially apply the input's Id to the Msg here
    , hasFocus = Nothing
    }
    []
    currentValue
```
Let me know if this solutions works for you, or perhaps I mistundersood your problem.

**Comment by razzeee** [comment]
Yes, sorry - I figured it out with help from the elm slack. Was confused by the update function.
Where the `value` of the input comes as last param, not as the first, as I thought.

Btw what's the best way to do `Input.defaultOptions` with no onInput message?

**Comment by abadi199** [comment]
You can just pass a `NoOp` Msg where you will just going to ignore that msg in your update function, like this:
```elm 
type Msg = NoOp 

Input.Text.input (Input.Text.defaultOptions (\_ -> NoOp) ...
```
I hope that helps.
I'm gonna close this issue now.
