### ISSUE TITLE
Update to elm 0.19

### ISSUE THREAD

**Issue by razzeee** [abadi199/elm-input-extra#16]

**Comment by razzeee** [comment]
So does this mean, this library is deprecated?

**Comment by FidelisClayton** [comment]
There is some work being done in this branch: https://github.com/abadi199/elm-input-extra/tree/0.19

**Comment by emarthinsen** [comment]
Any update on this? I'm working on upgrading an Elm 0.18 app.

**Comment by abadi199** [comment]
I'm still planing to update this package, but I'm not using Elm full time anymore :cry: , so the process is going to be slower. I'm always open for pull request :smiley:

**Comment by chevinbrown** [comment]
🙏 🙏 🙏 🙏 🙏 🙏 🙏 🙏 🙏

**Comment by chevinbrown** [comment]
@abadi199 have you considered pulling in some contributors to help? I see indicatrix/elm-input-extra is ready for 0.19...

**Comment by abadi199** [comment]
I reached out to them about making the PR, but I haven't heard from them again. I'll actually have time to continue working on this issue again this week, so hopefully we will have the 0.19 version in a couple of days.

**Comment by abadi199** [comment]
I just published version `5.2.2` that works with Elm 0.19 :confetti_ball: 
I'll close this issue now, and if you run into any issue with this version, please open a new issue.
