### ISSUE TITLE
Number input onInput message get's called 3 times

### ISSUE THREAD

**Issue by alexandru-calinoiu** [abadi199/elm-input-extra#23]
I've updated the number demo to output how many times the onInput message get's send

https://ellie-app.com/9hVrFFjqQyVa1

If you type a number in the first input and take a look at the logs, you will notice that the debug message get's printed 3 times. Sometimes the number get's doubled also or a zero get's added when switching to the logs.

**Comment by abadi199** [comment]
Fixed by #24 and published as [v5.2.4](https://package.elm-lang.org/packages/abadi199/elm-input-extra/5.2.4/)
