### ISSUE TITLE
Expose MaskedInput.Number module

### ISSUE THREAD

**Issue by szubtsovskiy** [abadi199/elm-input-extra#3]
Hey!

Thanks for the great job of bringing masked input into the Elm world. This is exactly I was searching for. 

Would it be possible for you to also expose MaskedInput.Number module? 

Thanks!

**Comment by abadi199** [comment]
Thanks for reporting this, I didn't realize that MaskedInput.Number is not exposed yet. I just push a new release (`4.3.0`) that exposes MaskedInput.Number.

**Comment by szubtsovskiy** [comment]
Great, thanks!
