### ISSUE TITLE
Input Placeholder

### ISSUE THREAD

**Issue by Bernardoow** [abadi199/elm-input-extra#4]
Hi, Abadin199 !

At input masked, I added placeholder.

It's a cool idea? If it's I can do in more places.
#5

**Comment by abadi199** [comment]
Hi Bernando,
Thanks for your contribution. It's a neat idea, but I believe you can also do this by adding `placeholder` as part of the `attributes` argument of the `input` functions.
Example:
```elm
MaskedInput.Text.input 
    MaskedInput.Text.defaultOptions 
    [ Html.placeholder "some placeholder text" ]
    model.currentState
    model.currentValue
```
Unless there's a reason you can't do that? I'm trying to keep the number of options you need to configure to a minimum.
