### ISSUE TITLE
Limit of Input Mask

### ISSUE THREAD

**Issue by Bernardoow** [abadi199/elm-input-extra#6]
Hi I thought  the length of the mask was limit of input.

Where I put check for length of input? At Msg?

Or it can be in component?

**Comment by abadi199** [comment]
Sorry I haven't responded sooner. I recommend you to ask questions on slack channel, just ping me there, my username is @abadi199, you will get a faster answer from me there.

To answer your question, the mask should be able to limit the length of your input, for example, if your mask is ####, then users should only be able to enter 4 characters. Do you have any particular example where this doesn't work?
