### ISSUE TITLE
Selected MultiSelect Option

### ISSUE THREAD

**Issue by thedumbtechguy** [abadi199/elm-input-extra#8]
Currently, we have a multiselect item defined as 

```elm
type alias Item =
    { value : String, text : String, enabled : Bool }
```

Is it possible to get an option to indicate that an item is selected
maybe something like

```elm
type alias Item =
    { value : String, text : String, enabled : Bool, selected: Maybe Bool }
```

or even pass a list of selected values to `MultiSelect.multiSelect`.

**Comment by abadi199** [comment]
You can already pass the selected values to `MultiSelect.multiselect`, the 3rd argument to that function is a `List String` which is the list of selected ids. You can see the example [here](https://github.com/abadi199/elm-input-extra/blob/1a4116812b0979c63bfbae9e18d960c80bc81bfb/demo/MultiSelectDemo.elm#L61)

**Comment by thedumbtechguy** [comment]
Oh. Now I just feel silly.
